name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:
      - name: Do Stuff
        run: |
          echo '----'
          echo '${{ github.event.issue.body }}'
          echo '----'
          echo '${{ fromJSON(github.event.issue.body) }}'
