name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Zip file
        run: |
          wget https://github.com/pbking/zip-extraction-practice/files/10561056/adventurer.zip
          
      - uses: montudor/action-zip@v1
        with:
          args:
            unzip -qq ./adventurer.zip -d ./adventurer

      - name: Do Stuff
        run: |
          ls -lR