name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Zip file
        run: |
          wget https://github.com/pbking/zip-extraction-practice/files/10572864/adventurer.zip
          
      - uses: montudor/action-zip@v1
        with:
          args:
            unzip -qq ./adventurer.zip -d ./adventurer

      - name: Do Stuff
        run: |
          sudo chown -R $USER:$USER .
          sudo rm ./adventurer.zip
          sudo ls -lR

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: Add adventurer to repo
          committer: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: add/adventurer
          delete-branch: true
          title: '[Add Theme] Adventurer'
          body: |
            Add Adventurer Theme
            - Excracted from zip
          labels: |
            add theme
          assignees: pbking
          reviewers: pbking
          team-reviewers: |
            owners
            maintainers
          draft: false