name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-zip
        with:
          text: ${{ github.event.issue.body }}
          regex: '\((.*?\.zip)\)'

      - name: Do Stuff
        if: ${{ steps.match-zip.outputs.group1 }}
        run: |
          echo '${{ steps.match-zip.outputs.group1 }}'
