name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:
      - name: Do Stuff
        run: |
          echo ${{ fromJSON(github.event) }}
          echo ${{ fromJSON(github.event.issue) }}
