name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:

      - uses: actions-ecosystem/action-regex-match@v2
        id: regex-match
        with:
          text: ${{ github.event.issue.body }}
          regex: '\((.*?)\.zip\)'

      - name: Do Stuff
        if: ${{ steps.regex-match.outputs.group1 }}
        env:
          zipfile: format('{filename}.zip', steps.regex-match.outputs.group1) 
        run: |
          echo '${{ zipfile }}'
