name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-url
        with:
          text: ${{ github.event.issue.body }}
          regex: '\((.*?\.zip)\)'

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-filename
        with:
          text: ${{ github.event.issue.body }}
          regex: '\(.*\/(.*?\.zip)\)'

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-theme-name
        with:
          text: ${{ github.event.issue.body }}
          regex: '\(.*\/(.*?)\.zip\)'
        
      - name: Download Zip
        if: ${{ steps.match-url.outputs.group1 }}
        run: |
          wget ${{ steps.match-url.outputs.group1 }}

      - name: Unzip Theme
        uses: montudor/action-zip@v1
        with:
          args:
            unzip -qq ./${{ steps.match-filename.outputs.group1 }} -d ./${{ steps.match-theme-name.outputs.group1 }}

      - name: Open Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo chown -R $USER:$USER .
          sudo rm ./${{ steps.match-filename.outputs.group1 }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config --global --add --bool push.autoSetupRemote true
          git checkout -b add/${{ steps.match-theme-name.outputs.group1 }}
          git add --all
          git commit -m "Adding Theme: [${{ steps.match-theme-name.outputs.group1 }}]"
          git push origin add/${{ steps.match-theme-name.outputs.group1 }}