name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "edited" ]

  issue_comment:
    type: [ "created", "edited" ]

jobs:
  extrakt:

    # We don't do anything on pull requests, which are also considered issues
    if: ${{ !github.event.issue.pull_request }}

    runs-on: ubuntu-latest
    steps:

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-url
        with:
          text: ${{ github.event.issue.body }}
          regex: '\((.*?\.zip)\)'
        env:
          ZIP_URL: ${{ steps.match-url.outputs.group1 }}

      - name: Show Results
        run: |
          echo '${{ ZIP_URL }}'