name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest
    steps:

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-url
        with:
          text: ${{ github.event.issue.body }}
          regex: '\((.*?\.zip)\)'

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-filename
        with:
          text: ${{ github.event.issue.body }}
          regex: '\(.*\/(.*?\.zip)\)'

      - uses: actions-ecosystem/action-regex-match@v2
        id: match-theme-name
        with:
          text: ${{ github.event.issue.body }}
          regex: '\(.*\/(.*?)\.zip\)'
        
      - name: Download Zip
        if: ${{ steps.match-url.outputs.group1 }}
        run: |
          wget ${{ steps.match-url.outputs.group1 }}

      - name: Unzip Theme
        uses: montudor/action-zip@v1
        with:
          args:
            unzip -qq ./${{ steps.match-filename.outputs.group1 }} -d ./${{ steps.match-theme-name.outputs.group1 }}