name: Extrakt a Theme

on:
  issues:
    types: [ "opened", "tagged", "edited" ]

  workflow_dispatch:
  
jobs:
  extrakt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Get Zip file
        run: |
          wget https://github.com/pbking/zip-extraction-practice/files/10572864/adventurer.zip
          
      - uses: montudor/action-zip@v1
        with:
          args:
            unzip -qq ./adventurer.zip -d ./adventurer

      - name: Do Stuff
        run: |
          sudo chown -R $USER:$USER .
          sudo rm ./adventurer.zip
          sudo ls -lR

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          destination_branch: "trunk"                      # If blank, default: master
          pr_title: "Pulling ${{ github.ref }} into master" # Title of pull request
          pr_body: |                                        # Full markdown support, requires pr_title to be set
            :crown: *An automated PR*

            _Created by [repo-sync/pull-request](https://github.com/repo-sync/pull-request)_
          pr_reviewer: "pbking"                         # Comma-separated list (no spaces)
          pr_assignee: "worker"                         # Comma-separated list (no spaces)
          pr_label: "auto-pr"                               # Comma-separated list (no spaces)
          pr_allow_empty: false                              # Creates pull request even if there are no changes